apiVersion: v1
kind: Service
metadata:
  name: ass2-webapp-app
  namespace: ass2
  labels:
    app: employees
spec:
  selector:
    app: employees
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
