apiVersion: apps/v1
kind: Deployment
metadata:
  name: ass2-webapp-deployment
  namespace: ass2-web
  labels:
    app: employeeswebapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: ass2-webapp-container
        image: 034644060220.dkr.ecr.us-east-1.amazonaws.com/assignment2-images-repo:Ass2webapp-v0.1
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: DBHOST
          value: "ass2-mysql-service.ass2.svc.cluster.local"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "Ass2Password"
        - name: DBPORT
          value: "3306"