apiVersion: apps/v1
kind: Deployment
metadata:
  name: ass2-webapp-deployment
  namespace: ass2
  labels:
    app: employees
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: app
        ports:
        - containerPort: 8080
          protocol: TCP
        image: 015937355141.dkr.ecr.us-east-1.amazonaws.com/mywebapp:v1.0
        env:
        - name: DBHOST
          value: "ass2-mysql-service.ass2.svc.cluster.local"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "Ass2Password"
        - name: DBPORT
          value: "3306"
