apiVersion: v1
kind: Service
metadata:
  name: ass2-mysql-service
  namespace: ass2
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  ports:
  - name: ass2-mysql-serviceport
    port: 3306
    targetPort: 3306
    protocol: TCP

