<<<<<<< HEAD
apiVersion: v1
kind: Pod
metadata:
  name: ass2-mysql-pod
  namespace: ass2
  labels:
    app: mysql

spec:
  containers:
  - name: ass2-mysql-container 
    image: 034644060220.dkr.ecr.us-east-1.amazonaws.com/assignment2-images-repo:Ass2-mysql-image-v0.1
    ports:
    - containerPort: 3306
      protocol: TCP
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "Ass2Password"
=======
apiVersion: apps/v1
kind: Deployment
>>>>>>> f53efa404df6cfcebf5e86b6856360fb66cfeb29
